socialmedia/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('login/', views.UserloginView.as_view(), name='user_login'),
]

socialmedia/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home, name='home'),

]

socialmedia/socialmedia/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

socialmedia/home/models.py
from django.db import models

# Create your models here.

socialmedia/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError

class UserRegisterForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password1 = forms.CharField(label='password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    password2 = forms.CharField(label='confirm password', widget=forms.PasswordInput(attrs={'class': 'form-control'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        user = User.objects.filter(email=email).exists()
        if user:
            raise ValidationError('this email already exist')
        return email

    def clean_username(self):
        username = self.cleaned_data['username']
        user = User.objects.filter(username=username).exists()
        if user:
            raise ValidationError('this username already exist')
        return username
    def clean(self):
        cd = super().clean()
        p1 = cd.get('password1')
        p2 = cd.get('password2')
        if p1 and p2 and p1 != p2:
            raise ValidationError('password must be match')

class UserLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))

socialmedia/home/views.py
from django.shortcuts import render
from django.http import HttpResponse

def home(request):
    return render(request, 'home/index.html')

# Create your views here.

socialmedia/accounts/templates/accounts/login.html
{% extends 'base.html'%}

{% block content %}
    <h2> login user</h2>
    <form action="" method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="login">
    </form>
{% endblock %}

socialmedia/accounts/templates/accounts/register.html
{% extends 'base.html'%}

{% block content %}
    <h2> Regist user</h2>
    <form action="" method="post" class="col-md-6" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="register">
    </form>
{% endblock %}

socialmedia/home/templates/home/index.html
{% extends 'base.html' %}


{% block content %}
    Index page
{% endblock %}

socialmedia/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>StackOverflow</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <style>
        .jumbotron{
        padding: 20px;
        margin-bottom:20px;
        background-color:#e9ecef;
        }
    </style>


</head>
<body>
  {% include 'inc/navbar.html' %}
  <div class="jumbotron">
      {% include 'inc/messages.html' %}
      {% block content %}{% endblock %}
  </div>
</body>
</html>

socialmedia/templates/inc/messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

socialmedia/templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <div class="navbar-nav">
    <a class="navbar-brand" href="{% url 'home:home' %}">Navbar</a>
    <a class="navbar-brand" href="{% url 'accounts:user_register' %}">Register</a>
      <a class="navbar-brand" href="{% url 'accounts:user_login' %}">Login</a>
    </div>
  </div>
</nav>